### PR TITLE
reduce cta paddings/margins on smaller devices

### LINKED ISSUE #47: Reduce CTA bar padding
# Problem 

Many counselors are using laptops with a smaller screen size where the cta bar gets in the way of some of the data/stats that they need to share on the site.

# Proposed Solution

Reduce the amount of space the links are taking up as well as setting some vh sizing with media queries.

### PR DESCRIPTION
**Pull request by joewhitsitt**
Resolves #47

Overrides to reduce paddings/margins for the CTA on smaller devices. Cute transitions for device re-sizing effect.

1380 x 799px display (updated 10:30 11/5)
Screen Shot 2020-11-05 at 10 29 36 AM

### CODE REVIEW

**Comment by bspeare** [comment]
I like what you did here.  I'm wondering if we should remove the border and row padding on the condensed version?

```
.cta-row__wrapper {
    padding: 0.3rem 0;
}
.cta-row__wrapper .bttn--outline {
    border: none;
}
```

Screen Shot 2020-11-05 at 9 01 44 AM

**Comment by joewhitsitt** [comment]
sure thing. updated screenshot

**Comment by bspeare** [comment]
This looks great.  I changed the base branch to `develop`so that we can merge it in there before `main`.   Once it is in `develop` we can share https://viewbook.admissions.uiowa.edu/latest/ to Scott for review.

**Review by bspeare — APPROVED** [review]
Looks great!

**Pull request merged**
